(()=>{
const SUPABASE_URL='https://shmbvkjzeqqxybweyowj.supabase.co';
const SUPABASE_KEY='sb_publishable_XEsFSPQsuq8AXxBVSnIKgQ_kbGegBtG';
const ANALYTICS_URL=SUPABASE_URL+'/functions/v1/vyrdict-analytics';
const LOCAL_KEY='vyrdict:saved';
const OWNER_KEY='vyrdict:saved-owner';
const SIGNIN_TRACK_KEY='vyrdict:analytics:signed-in';
let client=null,session=null,ready=false,syncing=null;

function localIds(){try{return [...new Set((JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')||[]).map(Number).filter(Number.isFinite))]}catch{return[]}}
function localOwner(){return localStorage.getItem(OWNER_KEY)||'guest'}
function writeLocal(ids,owner=localOwner()){const clean=[...new Set((ids||[]).map(Number).filter(Number.isFinite))];localStorage.setItem(LOCAL_KEY,JSON.stringify(clean));localStorage.setItem(OWNER_KEY,owner||'guest');try{if(typeof S!=='undefined'&&S?.saved){S.saved.clear();clean.forEach(id=>S.saved.add(id));if(typeof route==='function')setTimeout(()=>route(),0)}}catch{}return clean}
function track(event_name,event_value=null){if(window.VyrdictAnalytics?.send){window.VyrdictAnalytics.send(event_name,{event_value});return}try{fetch(ANALYTICS_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_name,path:location.pathname+(location.hash||''),product_slug:null,referrer:document.referrer||null,event_value}),keepalive:true}).catch(()=>{})}catch{}}
function dispatch(){window.dispatchEvent(new CustomEvent('vyrdict:account',{detail:{session,ready}}))}
function makeClient(){if(client)return client;if(!window.supabase?.createClient)return null;client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
function trackSignedInOnce(){if(!session?.user)return;try{if(sessionStorage.getItem(SIGNIN_TRACK_KEY)==='1')return;sessionStorage.setItem(SIGNIN_TRACK_KEY,'1')}catch{}track('account_signed_in')}
async function cloudIds(){const sb=makeClient();const {data,error}=await sb.rpc('get_my_saved_product_ids');if(error)throw error;return Array.isArray(data)?data.map(Number).filter(Number.isFinite):[]}
async function mergeGuestAndCloud(){if(!session?.user)return localIds();if(syncing)return syncing;syncing=(async()=>{const sb=makeClient();const userId=session.user.id;let local=localIds();const owner=localOwner();if(owner!=='guest'&&owner!==userId)local=[];let cloud=await cloudIds();const cloudSet=new Set(cloud);const additions=local.filter(id=>!cloudSet.has(id));const isGuestMerge=owner==='guest';if(additions.length){const {error}=await sb.rpc('sync_my_saved_products',{p_product_ids:additions});if(error)throw error;cloud=await cloudIds();if(isGuestMerge)track('guest_saves_synced',additions.length)}return writeLocal(cloud,userId)} )().finally(()=>{syncing=null});return syncing}
async function setCloudSave(productId,saved){if(!session?.user)return;const sb=makeClient();const {error}=await sb.rpc('set_my_product_save',{p_product_id:Number(productId),p_saved:!!saved});if(error){console.warn('VYRDICT save sync failed',error.message);return}localStorage.setItem(OWNER_KEY,session.user.id)}
function accountLabel(){return session?.user?.email?'Account ✓':'Account'}
function ensureNav(){const nav=document.querySelector('.header .nav');if(!nav)return;let a=nav.querySelector('[data-vyrdict-account]');if(!a){a=document.createElement('a');a.href='/account.html';a.setAttribute('data-vyrdict-account','');nav.appendChild(a)}a.textContent=accountLabel()}
function ensureAccountBack(){if(!/\/account\.html$/i.test(location.pathname))return;const shell=document.querySelector('.top .shell');if(!shell||shell.querySelector('[data-vyrdict-account-actions]'))return;const saves=shell.querySelector('a.back');const actions=document.createElement('div');actions.setAttribute('data-vyrdict-account-actions','');actions.style.cssText='display:flex;align-items:center;gap:8px;margin-left:auto';const back=document.createElement('a');back.className='back';back.href='/';back.setAttribute('data-vyrdict-account-back','');back.textContent='← Back';back.addEventListener('click',e=>{let sameOrigin=false;try{sameOrigin=!!document.referrer&&new URL(document.referrer).origin===location.origin}catch{}if(sameOrigin&&history.length>1){e.preventDefault();history.back()}});actions.appendChild(back);if(saves)actions.appendChild(saves);shell.appendChild(actions)}
function savedHost(){if(!location.hash.startsWith('#/saved'))return null;return document.querySelector('#app main .page.shell')||document.querySelector('#app main .shell')||document.querySelector('#app main')||document.querySelector('#app')}
function ensureSavedPrompt(){const old=document.querySelector('[data-vyrdict-sync-prompt]');const host=savedHost();if(!host){old?.remove();return}let box=old;if(!box){box=document.createElement('div');box.setAttribute('data-vyrdict-sync-prompt','');box.style.cssText='margin:18px auto 4px;padding:14px 16px;border:1px solid var(--line,#d8cec4);border-radius:16px;background:#fffaf4;display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap;font-family:Arial,sans-serif';host.prepend(box)}if(session?.user){box.innerHTML='<div><b style="font-size:11px;letter-spacing:.08em;text-transform:uppercase">✓ Saves synced</b><div style="margin-top:4px;color:#6e655d;font-size:11px">Your shortlist follows you across devices when you sign in with '+escapeHtml(session.user.email||'your email')+'.</div></div><a href="/account.html" style="color:#151310;font-size:10px;font-weight:900;text-decoration:none;border:1px solid #d8cec4;border-radius:999px;padding:8px 11px">Account →</a>'}else{box.innerHTML='<div><b style="font-size:11px;letter-spacing:.08em;text-transform:uppercase">Keep your saves everywhere</b><div style="margin-top:4px;color:#6e655d;font-size:11px">Guest saves stay on this browser. Sign in to sync them across devices.</div></div><a href="/account.html?next=saves" style="color:white;background:#151310;font-size:10px;font-weight:900;text-decoration:none;border-radius:999px;padding:9px 12px">Sign in / Create account →</a>'}}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderChrome(){ensureNav();ensureAccountBack();ensureSavedPrompt()}
async function refreshSession(){const sb=makeClient();if(!sb)return null;const {data}=await sb.auth.getSession();session=data.session||null;ready=true;if(session?.user){trackSignedInOnce();try{await mergeGuestAndCloud()}catch(e){console.warn('VYRDICT initial save merge failed',e?.message||e)}}renderChrome();dispatch();return session}
async function init(){const sb=makeClient();if(!sb)return;await refreshSession();sb.auth.onAuthStateChange((event,next)=>{session=next||null;ready=true;setTimeout(async()=>{if(session?.user){if(event==='SIGNED_IN'||event==='INITIAL_SESSION'||event==='TOKEN_REFRESHED')trackSignedInOnce();try{await mergeGuestAndCloud()}catch(e){console.warn('VYRDICT save merge failed',e?.message||e)}}renderChrome();dispatch()},0)});document.addEventListener('click',e=>{const b=e.target.closest?.('[data-save]');if(!b)return;const id=Number(b.dataset.save);if(!Number.isFinite(id))return;setTimeout(()=>{const saved=localIds().includes(id);if(session?.user)setCloudSave(id,saved);else localStorage.setItem(OWNER_KEY,'guest')},0)},{passive:true});const rerender=()=>setTimeout(renderChrome,80);addEventListener('hashchange',rerender);addEventListener('popstate',rerender);document.addEventListener('click',rerender,{passive:true});[200,700,1600].forEach(ms=>setTimeout(renderChrome,ms))}
window.VyrdictAccount={get client(){return client},get session(){return session},get ready(){return ready},refreshSession,mergeGuestAndCloud,localIds,writeLocal,track,async signOut(){const sb=makeClient();if(sb)await sb.auth.signOut();session=null;try{sessionStorage.removeItem(SIGNIN_TRACK_KEY)}catch{}writeLocal([],'guest');track('account_signed_out');renderChrome();dispatch()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();