(()=>{
  if(window.__vyrdictProductShellV13)return;
  window.__vyrdictProductShellV13=1;
  const match=decodeURIComponent(location.pathname).match(/^\/product\/([^/]+)\/?$/i);if(!match)return;
  const slug=match[1],clean='/product/'+encodeURIComponent(slug)+'/';
  const BUNDLE='https://shmbvkjzeqqxybweyowj.supabase.co/functions/v1/vyrdict-bundle-fast?v=15';
  const CACHE_KEY='vyrdict:bundle-cache:v15';
  const schema=document.querySelector('script[type="application/ld+json"]')?.textContent||'';
  const fallbackTitle=document.querySelector('.seo-fallback h1')?.textContent?.trim()||slug.replaceAll('-',' ');
  const seo={title:document.title,description:document.querySelector('meta[name="description"]')?.content||'',canonical:document.querySelector('link[rel="canonical"]')?.href||('https://vyrdict.com'+clean),ogTitle:document.querySelector('meta[property="og:title"]')?.content||document.title,ogDescription:document.querySelector('meta[property="og:description"]')?.content||'',ogImage:document.querySelector('meta[property="og:image"]')?.content||'https://vyrdict.com/vyrdict-social-preview.jpg',schema};
  const attr=s=>String(s||'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]));
  const save=d=>{try{if(d?.html)localStorage.setItem(CACHE_KEY,JSON.stringify({ts:Date.now(),html:d.html}))}catch{}};
  async function bundle(){
    try{const c=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(c?.html&&Date.now()-Number(c.ts||0)<5*60*1000){const refresh=()=>fetch(BUNDLE,{cache:'default'}).then(r=>r.ok?r.json():null).then(save).catch(()=>{});if('requestIdleCallback'in window)requestIdleCallback(refresh,{timeout:1800});else setTimeout(refresh,700);return{html:c.html}}}catch{}
    let last;for(let i=0;i<3;i++){try{const r=await fetch(BUNDLE,{cache:'default'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(d?.html){save(d);return d}throw new Error('Missing bundle')}catch(e){last=e;if(i<2)await new Promise(x=>setTimeout(x,[100,250][i]))}}throw last||new Error('bundle')
  }
  function patchApp(h){
    h=h.replaceAll('order=viral_score.desc,worth_score.desc&limit=250','order=viral_score.desc,worth_score.desc&limit=1000').replaceAll('product_collections?select=product_id,collection_id&limit=500','product_collections?select=product_id,collection_id&limit=5000');
    const old="let sel='id,slug,brand,name,category,subcategory,viral_score,worth_score,verdict,viral_status,viral_summary,product_description,image_url';[S.p,S.c,S.l]=await Promise.all([api(`products?select=${sel}&is_active=eq.true&evidence_status=eq.verified&order=viral_score.desc,worth_score.desc&limit=1000`),api('collections?select=id,slug,name,description,collection_type&is_active=eq.true'),api('product_collections?select=product_id,collection_id&limit=5000')]);route()}";
    const fast="let sel='id,slug,brand,name,category,subcategory,viral_score,worth_score,verdict,viral_status,viral_summary,product_description,image_url';const dm=(location.pathname||'').match(/^\\/product\\/([^/?#]+)/);if(dm){const ds=decodeURIComponent(dm[1]),bd=window.__VYRDICT_BOOT_DATA;const cp=bd?.p?.find?.(x=>x.slug===ds);if(cp){S.p=[cp];S.c=bd.c||[];S.l=(bd.l||[]).filter(x=>Number(x.product_id)===Number(cp.id));route();return}S.p=await api(`products?select=${sel}&slug=eq.${encodeURIComponent(ds)}&is_active=eq.true&evidence_status=eq.verified&limit=1`);S.c=[];S.l=S.p[0]?await api(`product_collections?select=product_id,collection_id&product_id=eq.${S.p[0].id}&limit=20`):[];route();return}[S.p,S.c,S.l]=await Promise.all([api(`products?select=${sel}&is_active=eq.true&evidence_status=eq.verified&order=viral_score.desc,worth_score.desc&limit=1000`),api('collections?select=id,slug,name,description,collection_type&is_active=eq.true'),api('product_collections?select=product_id,collection_id&limit=5000')]);route()}";
    h=h.replace(old,fast);
    h=h.replace("async function route(){let raw=location.hash.startsWith('#/')?location.hash.slice(1):'/';let qpos=raw.indexOf('?');let path=qpos>=0?raw.slice(0,qpos):raw;let query=qpos>=0?raw.slice(qpos+1):'';","async function route(){let path=location.pathname||'/';let query=(location.search||'').replace(/^\\?/, '');");
    h=h.replace("function nav(u){let from=location.hash.startsWith('#/')?location.hash.slice(1):'/';history.pushState({vyrdict:true,from},'',location.pathname+location.search+'#'+u);route()}","function nav(u){let from=location.pathname+location.search;history.pushState({vyrdict:true,from},'',u);route()}");
    h=h.replace("function smartBack(){if(history.state?.vyrdict&&history.state?.from){history.back()}else{history.replaceState({vyrdict:true,from:null},'',location.pathname+location.search+'#/');route()}}","function smartBack(){if(history.state?.vyrdict&&history.state?.from){history.back()}else{history.replaceState({vyrdict:true,from:null},'','/');route()}}");
    h=h.replace("async function boot(){if(!location.hash.startsWith('#/'))history.replaceState({vyrdict:true,from:null},'',location.pathname+location.search+'#/');else if(!history.state?.vyrdict)history.replaceState({vyrdict:true,from:null},'',location.href);","async function boot(){if(location.hash.startsWith('#/')){let legacy=location.hash.slice(1);history.replaceState({vyrdict:true,from:null},'',legacy)}else if(!history.state?.vyrdict)history.replaceState({vyrdict:true,from:null},'',location.pathname+location.search);");
    h=h.replaceAll("decodeURIComponent(location.hash||'').match(/#\\/product\\/([^?#]+)/i)","decodeURIComponent(location.pathname||'').match(/\\/product\\/([^/?#]+)/i)");
    return h;
  }
  (async()=>{try{
    const d=await bundle();if(!d?.html)throw new Error('html');let h=patchApp(d.html);
    const schemaTag=seo.schema?'<script type="application/ld+json">'+seo.schema.replace(/<\/script/gi,'<\\/script')+'<\/script>':'';
    const tags='<base href="/"><title>'+attr(seo.title)+'</title><meta name="description" content="'+attr(seo.description)+'"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="'+attr(seo.canonical)+'"><meta property="og:site_name" content="VYRDICT"><meta property="og:type" content="product"><meta property="og:url" content="'+attr(seo.canonical)+'"><meta property="og:title" content="'+attr(seo.ogTitle)+'"><meta property="og:description" content="'+attr(seo.ogDescription)+'"><meta property="og:image" content="'+attr(seo.ogImage)+'"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="'+attr(seo.ogTitle)+'"><meta name="twitter:description" content="'+attr(seo.ogDescription)+'"><meta name="twitter:image" content="'+attr(seo.ogImage)+'">'+schemaTag;
    h=h.replace(/<title[\s\S]*?<\/title>/i,'').replace(/<meta[^>]+name=["']description["'][^>]*>/i,'').replace(/<link[^>]+rel=["']canonical["'][^>]*>/i,'');h=h.replace('<head>','<head>'+tags);
    const cover='<div id="vyrdict-product-transition" role="status" aria-live="polite" style="position:fixed;inset:0;z-index:2147483647;background:#f4ede5;display:grid;place-items:center;font-family:Arial,Helvetica,sans-serif;color:#171511"><div style="width:min(420px,calc(100% - 40px));background:#fffdf8;border:1px solid #d8cec4;border-radius:24px;padding:28px;text-align:center;box-shadow:0 18px 55px rgba(58,43,32,.08)"><div style="font:950 27px/1 Arial,Helvetica,sans-serif;letter-spacing:-1.6px;display:inline-flex;align-items:flex-end">VYRDICT<span style="width:7px;height:7px;background:#e65f72;display:inline-block;margin:0 0 2px 2px"></span></div><div style="margin-top:14px;font:800 10px/1.4 Arial,Helvetica,sans-serif;letter-spacing:.08em;text-transform:uppercase;color:#6d675f">Loading the verdict…</div></div></div>';
    const tail='<script src="/navigation-guard.js?v=1" defer><\/script><script src="/product-fast.js?v=8" defer><\/script><script src="/analytics.js?v=perf-3" defer><\/script><script src="/product-detail-consistency.js?v=3" defer><\/script><script src="/market-completeness-fix.js?v=1" defer><\/script><script src="/social-links-fix.js?v=7" defer><\/script><script src="/affiliate-routing.js?v=1" defer><\/script><script>(()=>{const c=document.getElementById("vyrdict-product-transition");if(!c)return;let n=0;const ready=()=>{const a=document.getElementById("app"),hero=document.querySelector(".productHero");const text=(a?.textContent||"").trim();if((hero&&a&&text.length>100&&!/loading/i.test(text))||n++>160){requestAnimationFrame(()=>requestAnimationFrame(()=>c.remove()));return}setTimeout(ready,25)};ready()})();<\/script>';
    h=h.replace('<body>','<body>'+cover);h=h.replace('</body>',tail+'</body>');document.open();document.write(h);document.close();
  }catch(e){console.error('VYRDICT product shell',e)}})();
})();